AWSTemplateFormatVersion: 2010-09-09
Parameters:
  vpc2StackName: # ParameterKey
    Description: "cfn-vpc2"
    Type: String
    Default: "cfn-vpc2-stack"
Resources:
  vpc2customSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "cloudklaxon-master vpc2 Custom Security Group"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: "0.0.0.0/0"
      VpcId:
        Fn::ImportValue: !Sub ${vpc2StackName}-VPC2ID
      Tags:
        - Key: "Name"
          Value: "cloudklaxon Master vpc2 Security Group"
Outputs:
  vpc2customSecurityGroupID: # LogicalID
    Description: "cloudklaxon Master vpc2 SecurityGroup ID"
    Value: !Ref vpc2customSecurityGroup # the value of export is here
    Export:
      Name: !Sub ${AWS::StackName}-vpc2SecurityID # the name of the security stack export
