AWSTemplateFormatVersion: 2010-09-09
Parameters:
  vpc1StackName:
    Description: "cfn-vpc1-stack"
    Type: String
    Default: cfn-vpc1-stack
  vpc1securityStackName:
    Description: "cfn-vpc1-security-stack"
    Type: String
    Default: cfn-vpc1-securitygroup-stack
Resources:
  vpc1publicInstance1:
    Type: "AWS::EC2::Instance"
    Properties:
      SubnetId:
        Fn::ImportValue: !Sub ${vpc1StackName}-vpc1publicSubnet1ID
      ImageId: ami-0d058fe428540cd89
      InstanceType: t2.micro
      KeyName: cloudklaxon-key
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${vpc1securityStackName}-vpc1SecurityID
      Tags:
        - Key: "Name"
          Value: "vpc1-public-instance-1"
Outputs:
  vpc1publicInstanceDNS:
    Description: DNS Name of VPC1 Public Instance1
    Value: !GetAtt vpc1publicInstance1.PublicDnsName
