AWSTemplateFormatVersion: 2010-09-09
Parameters:
  vpc1StackName: # ParameterKey
    Description: "cfn-vpc1"
    Type: String
    Default: "cfn-vpc1-stack"
Resources:
  vpc1customSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "cloudklaxon-master vpc1 Custom Security Group"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: "0.0.0.0/0"
      VpcId:
        Fn::ImportValue: !Sub ${vpc1StackName}-VPC1ID
      Tags:
        - Key: "Name"
          Value: "cloudklaxon Master vpc1 Security Group"
Outputs:
  vpc1customSecurityGroupID: # LogicalID
    Description: "cloudklaxon Master vpc1 SecurityGroup ID"
    Value: !Ref vpc1customSecurityGroup # the value of export is here
    Export:
      Name: !Sub ${AWS::StackName}-vpc1SecurityID # the name of the security stack export
