AWSTemplateFormatVersion: 2010-09-09
Resources:
  cloudklaxonMasterVpc2: #create a VPC cloudklaxonMasterVpc2
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "172.16.0.0/16"
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: "default"
      Tags:
        - Key: "Name"
          Value: "cloudklaxon-master-vpc2"
  vpc2publicSubnet1: #add a subnet publicsubnet1
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-southeast-1a"
      CidrBlock: "172.16.1.0/24"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: "Name"
          Value: "mastervpc2-public-subnet1"
      VpcId: !Ref cloudklaxonMasterVpc2
  vpc2publicSubnet2: #add a subnet publicsubnet2
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-southeast-1b"
      CidrBlock: "172.16.2.0/24"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: "Name"
          Value: "mastervpc2-public-subnet2"
      VpcId: !Ref cloudklaxonMasterVpc2
  vpc2publicSubnet3: #add a subnet publicsubnet3
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-southeast-1c"
      CidrBlock: "172.16.3.0/24"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: "Name"
          Value: "mastervpc2-public-subnet3"
      VpcId: !Ref cloudklaxonMasterVpc2
  vpc2routeTableForPublicSubnets: # public subnets routetable
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: "Name"
          Value: "vpc2-route-table-publicSubnets"
      VpcId: !Ref cloudklaxonMasterVpc2
  publicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref vpc2publicSubnet1
      RouteTableId: !Ref vpc2routeTableForPublicSubnets
  publicSubnet2RouteTableAssociation: # associate publicSubnet2 to route table
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref vpc2publicSubnet2
      RouteTableId: !Ref vpc2routeTableForPublicSubnets
  publicSubnet3RouteTableAssociation: # associate publicSubnet3 to route table
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref vpc2publicSubnet3
      RouteTableId: !Ref vpc2routeTableForPublicSubnets
  cloudklaxonvpc2IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: "Name"
          Value: "cloudklaxon vpc2 igw"
  attachVPCAndIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref cloudklaxonvpc2IGW
      VpcId: !Ref cloudklaxonMasterVpc2
  defaultRouteToIGW:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref cloudklaxonvpc2IGW
      RouteTableId: !Ref vpc2routeTableForPublicSubnets
Outputs:
  cloudklaxonMasterVpc2ID: # logicalID
    Description: "cloudklaxon Master VPC2 ID"
    Value: !Ref cloudklaxonMasterVpc2 # the value of cloudklaxonMasterVpc2 export is here
    Export:
      Name: !Sub ${AWS::StackName}-VPC2ID # the name of cloudklaxonMasterVpc2 export
  vpc2publicSubnet1ID: #logicalID
    Description: "cloudklaxon Master VPC2 publicsubnet1 ID"
    Value: !Ref vpc2publicSubnet1 # the value of export is here
    Export:
      Name: !Sub ${AWS::StackName}-vpc2publicSubnet1ID # the name of vpc2publicSubnet1 export
  vpc2publicSubnet2ID: #logicalID
    Description: "cloudklaxon Master VPC2 publicsubnet2 ID"
    Value: !Ref vpc2publicSubnet2 # the value of export is here
    Export:
      Name: !Sub ${AWS::StackName}-vpc2publicSubnet2ID # the name of  export
  vpc2publicSubnet3ID: #logicalID
    Description: "cloudklaxon Master VPC2 publicsubnet3 ID"
    Value: !Ref vpc2publicSubnet3 # the value of export is here
    Export:
      Name: !Sub ${AWS::StackName}-vpc2publicSubnet3ID # the name of export
  vpc2routeTableForPublicSubnets: #logicalID same logicalID with routeTable but no error
    Description: "cloudklaxon vpc2 routeTable ID"
    Value: !Ref vpc2routeTableForPublicSubnets # the vaule of export is here
    Export:
      Name: !Sub ${AWS::StackName}-vpc2routeTableID
  vpc2CidrBlockID:
    Description: "cloudklaxon Master VPC2 CidrBlock ID"
    Value: !GetAtt cloudklaxonMasterVpc2.CidrBlock
    Export:
      Name: !Sub ${AWS::StackName}-VPC2CIDR # the name of export
